In [36]:
import pandas as pd
messages = pd.read_csv("SMSSpamCollection", sep='\t', names=["label","message"])

In [37]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [38]:
from nltk.corpus import stopwords 
import re
from nltk.stem import WordNetLemmatizer
ps=WordNetLemmatizer()

In [39]:
corpus=[]
for i in range(0,len(messages)):
    review= re.sub("[^a-zA-Z]"," ",messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=" ".join(review)
    corpus.append(review)

In [40]:
print(corpus[:10])

['go jurong point crazy available bugis n great world la e buffet cine got amore wat', 'ok lar joking wif u oni', 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply', 'u dun say early hor u c already say', 'nah think go usf life around though', 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv', 'even brother like speak treat like aid patent', 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune', 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour', 'mobile month u r entitled update latest colour mobile camera free call mobile update co free']

In [41]:
#create BOW
from sklearn.feature_extraction.text import CountVectorizer
#for binary BOW enable binary=TRUE
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
X=cv.fit_transform(corpus).toarray()

In [42]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,formatter=dict(float=lambda x: "%.3g" % x))
X[:10]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [43]:
cv.vocabulary_

{'go': 768,
 'point': 1623,
 'crazy': 437,
 'available': 108,
 'bugis': 217,
 'great': 813,
 'world': 2440,
 'la': 1046,
 'cine': 340,
 'got': 804,
 'wat': 2351,
 'ok': 1479,
 'lar': 1059,
 'joking': 1003,
 'wif': 2403,
 'ok lar': 1481,
 'free': 693,
 'entry': 594,
 'wkly': 2426,
 'comp': 390,
 'win': 2408,
 'cup': 446,
 'final': 658,
 'st': 1970,
 'may': 1241,
 'text': 2079,
 'receive': 1728,
 'question': 1694,
 'std': 1985,
 'txt': 2189,
 'rate': 1707,
 'apply': 73,
 'free entry': 698,
 'entry wkly': 596,
 'std txt': 1986,
 'txt rate': 2195,
 'rate apply': 1708,
 'dun': 552,
 'say': 1814,
 'early': 559,
 'already': 47,
 'nah': 1379,
 'think': 2099,
 'usf': 2274,
 'life': 1118,
 'around': 84,
 'though': 2107,
 'freemsg': 705,
 'hey': 875,
 'darling': 464,
 'week': 2372,
 'word': 2435,
 'back': 127,
 'like': 1123,
 'fun': 724,
 'still': 1988,
 'tb': 2058,
 'xxx': 2468,
 'send': 1848,
 'even': 604,
 'brother': 208,
 'speak': 1955,
 'treat': 2168,
 'per': 1552,
 'request': 1759,
 'melle': 1256,
 'oru': 1522,
 'set': 1865,
 'callertune': 265,
 'caller': 262,
 'press': 1653,
 'copy': 420,
 'friend': 711,
 'per request': 1556,
 'set callertune': 1866,
 'callertune caller': 266,
 'caller press': 263,
 'press copy': 1654,
 'copy friend': 421,
 'friend callertune': 712,
 'winner': 2413,
 'valued': 2285,
 'network': 1406,
 'customer': 452,
 'selected': 1840,
 'prize': 1664,
 'reward': 1770,
 'claim': 343,
 'call': 234,
 'code': 361,
 'valid': 2282,
 'hour': 919,
 'claim call': 344,
 'call claim': 238,
 'claim code': 345,
 'valid hour': 2283,
 'mobile': 1310,
 'month': 1329,
 'entitled': 592,
 'update': 2233,
 'latest': 1071,
 'colour': 375,
 'camera': 272,
 'co': 358,
 'entitled update': 593,
 'update latest': 2235,
 'latest colour': 1073,
 'free call': 696,
 'call mobile': 249,
 'mobile update': 1318,
 'update co': 2234,
 'co free': 359,
 'gonna': 789,
 'home': 902,
 'soon': 1945,
 'want': 2335,
 'talk': 2053,
 'stuff': 2015,
 'anymore': 63,
 'tonight': 2151,
 'enough': 588,
 'today': 2135,
 'chance': 310,
 'cash': 291,
 'pound': 1638,
 'cost': 423,
 'day': 470,
 'reply': 1750,
 'hl': 887,
 'info': 961,
 'chance win': 312,
 'win cash': 2409,
 'reply hl': 1752,
 'hl info': 888,
 'urgent': 2262,
 'membership': 1259,
 'www': 2456,
 'net': 1403,
 'pobox': 1618,
 'ldnw': 1087,
 'week free': 2374,
 'txt word': 2198,
 'searching': 1826,
 'right': 1772,
 'thank': 2090,
 'promise': 1677,
 'wont': 2434,
 'take': 2049,
 'help': 873,
 'wonderful': 2432,
 'blessing': 168,
 'time': 2120,
 'date': 467,
 'sunday': 2028,
 'use': 2270,
 'credit': 439,
 'click': 352,
 'wap': 2348,
 'link': 1132,
 'next': 1420,
 'message': 1265,
 'http': 928,
 'com': 378,
 'oh': 1475,
 'watching': 2355,
 'eh': 570,
 'remember': 1743,
 'name': 1381,
 'yes': 2484,
 'naughty': 1389,
 'make': 1209,
 'wet': 2392,
 'fine': 665,
 'way': 2359,
 'feel': 646,
 'england': 584,
 'dont': 531,
 'miss': 1293,
 'goal': 779,
 'team': 2063,
 'news': 1419,
 'ur': 2238,
 'national': 1385,
 'eg': 568,
 'try': 2177,
 'wq': 2450,
 'dont miss': 533,
 'seriously': 1861,
 'going': 783,
 'ha': 840,
 'ha ha': 841,
 'pay': 1547,
 'first': 669,
 'da': 457,
 'stock': 1990,
 'comin': 386,
 'aft': 25,
 'finish': 667,
 'lunch': 1194,
 'str': 2008,
 'lor': 1164,
 'ard': 79,
 'smth': 1926,
 'alright': 48,
 'meet': 1250,
 'eat': 563,
 'really': 1723,
 'hungry': 933,
 'tho': 2106,
 'suck': 2022,
 'mark': 1227,
 'getting': 752,
 'worried': 2441,
 'know': 1039,
 'sick': 1888,
 'turn': 2185,
 'pizza': 1580,
 'lol': 1152,
 'always': 51,
 'catch': 299,
 'bus': 219,
 'egg': 569,
 'tea': 2061,
 'eating': 565,
 'mom': 1324,
 'left': 1099,
 'dinner': 512,
 'love': 1170,
 'amp': 54,
 'car': 284,
 'let': 1110,
 'room': 1783,
 'let know': 1112,
 'work': 2436,
 'feel like': 647,
 'wait': 2320,
 'sure': 2037,
 'live': 1138,
 'yeah': 2478,
 'child': 332,
 'till': 2119,
 'cheer': 329,
 'yeah got': 2479,
 'tell': 2068,
 'anything': 65,
 'tell anything': 2069,
 'quick': 1695,
 'thanks': 2091,
 'subscription': 2021,
 'ringtone': 1775,
 'uk': 2211,
 'charged': 319,
 'please': 1593,
 'confirm': 401,
 'replying': 1755,
 'mobile charged': 1312,
 'yup': 2498,
 'look': 1158,
 'timing': 2126,
 'msg': 1350,
 'learn': 1092,
 'nd': 1390,
 'lesson': 1109,
 'go home': 773,
 'oops': 1502,
 'roommate': 1784,
 'done': 530,
 'see': 1834,
 'letter': 1113,
 'decide': 485,
 'anything lor': 66,
 'hello': 872,
 'saturday': 1808,
 'texting': 2087,
 'decided': 486,
 'tomo': 2143,
 'trying': 2178,
 'pls': 1600,
 'ahead': 33,
 'wanted': 2345,
 'weekend': 2377,
 'abiola': 1,
 'great weekend': 815,
 'forget': 685,
 'need': 1396,
 'crave': 436,
 'sweet': 2043,
 'want need': 2340,
 'need crave': 1398,
 'tried': 2169,
 'sm': 1919,
 'nokia': 1434,
 'camcorder': 268,
 'delivery': 495,
 'tomorrow': 2144,
 'call reply': 254,
 'nokia mobile': 1438,
 'mobile free': 1315,
 'free camcorder': 697,
 'please call': 1594,
 'delivery tomorrow': 496,
 'seeing': 1837,
 'hope': 906,
 'man': 1217,
 'well': 2384,
 'lt': 1184,
 'gt': 820,
 'inch': 956,
 'lt gt': 1186,
 'missed': 1297,
 'missed call': 1298,
 'get': 743,
 'nigeria': 1425,
 'hopefully': 910,
 'tyler': 2206,
 'could': 428,
 'maybe': 1243,
 'ask': 93,
 'bit': 164,
 'hospital': 914,
 'kept': 1023,
 'telling': 2072,
 'weak': 2365,
 'want go': 2338,
 'saw': 1813,
 'class': 350,
 'first time': 670,
 'usually': 2277,
 'run': 1791,
 'half': 846,
 'almost': 45,
 'whole': 2400,
 'second': 1829,
 'like lt': 1126,
 'fyi': 727,
 'ride': 1771,
 'morning': 1334,
 'place': 1581,
 'wow': 2449,
 'never': 1410,
 'thought': 2108,
 'liked': 1127,
 'since': 1897,
 'best': 153,
 'happy': 856,
 'sorry': 1946,
 'give': 760,
 'ac': 4,
 'new': 1411,
 'red': 1733,
 'play': 1586,
 'ice': 940,
 'correct': 422,
 'end': 577,
 'sm ac': 1920,
 'yesterday': 2489,
 'find': 661,
 'congrats': 402,
 'year': 2481,
 'special': 1958,
 'cinema': 341,
 'pas': 1544,
 'etc': 600,
 'bx': 225,
 'ip': 977,
 'pm': 1612,
 'etc free': 601,
 'bx ip': 226,
 'ip pm': 978,
 'later': 1068,
 'meeting': 1252,
 'sorry call': 1947,
 'call later': 247,
 'later meeting': 1069,
 'reached': 1716,
 'pick': 1570,
 'move': 1341,
 'pain': 1535,
 'way home': 2360,
 'good': 791,
 'joke': 1002,
 'girl': 758,
 'situation': 1908,
 'part': 1540,
 'checking': 328,
 'took': 2153,
 'forever': 684,
 'come': 381,
 'ok come': 1480,
 'double': 536,
 'check': 326,
 'hair': 845,
 'said': 1800,
 'wun': 2455,
 'cut': 454,
 'short': 1880,
 'nice': 1423,
 'pleased': 1597,
 'following': 679,
 'review': 1769,
 'mob': 1308,
 'awarded': 116,
 'bonus': 180,
 'awarded bonus': 117,
 'prize call': 1665,
 'song': 1941,
 'frnds': 718,
 'rply': 1789,
 'send ur': 1854,
 'complimentary': 395,
 'trip': 2171,
 'dis': 516,
 'ur awarded': 2239,
 'hear': 865,
 'plane': 1583,
 'wah': 2319,
 'lucky': 1191,
 'save': 1812,
 'money': 1328,
 'hee': 869,
 'finished': 668,
 'hi': 879,
 'babe': 123,
 'im': 948,
 'wanna': 2334,
 'something': 1937,
 'xx': 2467,
 'hi babe': 880,
 'waiting': 2322,
 'machan': 1200,
 'call free': 240,
 'thats': 2094,
 'cool': 418,
 'respect': 1760,
 'thats cool': 2095,
 'people': 1551,
 'much': 1364,
 'pa': 1529,
 'looking': 1162,
 'job': 996,
 'ta': 2048,
 'ah': 31,
 'hi hi': 882,
 'stop': 1994,
 'urgnt': 2268,
 'real': 1722,
 'yo': 2493,
 'ticket': 2117,
 'one': 1497,
 'used': 2271,
 'started': 1978,
 'came': 270,
 'bed': 145,
 'coin': 366,
 'gotta': 810,
 'kano': 1014,
 'il': 946,
 'download': 538,
 'wen': 2387,
 'wen ur': 2388,
 'stand': 1973,
 'close': 354,
 'another': 59,
 'night': 1426,
 'spent': 1964,
 'late': 1067,
 'afternoon': 26,
 'mean': 1245,
 'moro': 1337,
 'smile': 1922,
 'pleasure': 1598,
 'trouble': 2172,
 'rain': 1702,
 'sum': 2025,
 'hurt': 936,
 'someone': 1934,
 'smiling': 1923,
 'service': 1862,
 'representative': 1757,
 'guaranteed': 828,
 'call customer': 239,
 'customer service': 453,
 'service representative': 1864,
 'representative pm': 1758,
 'pm guaranteed': 1614,
 'guaranteed cash': 830,
 'cash prize': 296,
 'havent': 863,
 'planning': 1585,
 'buy': 222,
 'show': 1881,
 'simply': 1896,
 'password': 1545,
 'po': 1616,
 'box': 196,
 'mk': 1303,
 'free ringtone': 702,
 'po box': 1617,
 'movie': 1342,
 'abt': 3,
 'wat abt': 2352,
 'load': 1143,
 'loan': 1144,
 'wk': 2424,
 'forgot': 686,
 'appointment': 74,
 'shower': 1884,
 'cause': 300,
 'prob': 1670,
 'need get': 1400,
 'get home': 746,
 'coffee': 365,
 'nothing': 1451,
 'else': 572,
 'okay': 1491,
 'price': 1656,
 'long': 1155,
 'legal': 1101,
 'ave': 109,
 'gone': 788,
 'driving': 546,
 'test': 2078,
 'yet': 2490,
 'guess': 836,
 'gave': 733,
 'boston': 191,
 'men': 1260,
 'changed': 314,
 'search': 1825,
 'location': 1146,
 'nyc': 1465,
 'cuz': 456,
 'page': 1533,
 'umma': 2215,
 'lot': 1168,
 'dear': 481,
 'love lot': 1174,
 'wish': 2415,
 'birthday': 162,
 'making': 1215,
 'truly': 2174,
 'aight': 35,
 'hit': 885,
 'would': 2447,
 'address': 17,
 'computer': 396,
 'old': 1494,
 'better': 155,
 'worry': 2442,
 'busy': 221,
 'thing': 2098,
 'scared': 1818,
 'mah': 1204,
 'contact': 407,
 'last': 1062,
 'draw': 539,
 'hr': 926,
 'ppm': 1644,
 'trying contact': 2179,
 'contact last': 410,
 'last weekend': 1066,
 'weekend draw': 2378,
 'draw show': 541,
 'show prize': 1882,
 'prize guaranteed': 1667,
 'guaranteed call': 829,
 'code valid': 364,
 'valid hr': 2284,
 'hr ppm': 927,
 'wa': 2318,
 'anyway': 69,
 'juz': 1012,
 'tt': 2181,
 'eatin': 564,
 'weight': 2382,
 'haha': 843,
 'happened': 852,
 'entered': 590,
 'cabin': 228,
 'bos': 189,
 'felt': 649,
 'askd': 94,
 'invited': 972,
 'apartment': 70,
 'went': 2389,
 'entered cabin': 591,
 'cabin pa': 229,
 'pa said': 1530,
 'said happy': 1801,
 'happy day': 858,
 'day bos': 471,
 'bos felt': 190,
 'felt special': 650,
 'special askd': 1959,
 'askd lunch': 95,
 'lunch lunch': 1196,
 'lunch invited': 1195,
 'invited apartment': 973,
 'apartment went': 71,
 'specially': 1961,
 'holiday': 898,
 'flight': 676,
 'inc': 955,
 'operator': 1504,
 'min': 1275,
 'winner specially': 2414,
 'specially selected': 1962,
 'selected receive': 1841,
 'speak live': 1956,
 'live operator': 1140,
 'operator claim': 1505,
 'must': 1376,
 'friday': 710,
 'needed': 1402,
 'hmm': 890,
 'uncle': 2219,
 'informed': 963,
 'paying': 1549,
 'school': 1820,
 'directly': 515,
 'food': 681,
 'private': 1662,
 'account': 8,
 'statement': 1980,
 'unredeemed': 2227,
 'identifier': 943,
 'expires': 625,
 'private account': 1663,
 'account statement': 9,
 'statement show': 1981,
 'point claim': 1625,
 'call identifier': 243,
 'identifier code': 944,
 'code expires': 362,
 'landline': 1054,
 'urgent mobile': 2265,
 'mobile awarded': 1311,
 'bonus caller': 181,
 'caller prize': 264,
 'contact call': 408,
 'call landline': 246,
 'voda': 2305,
 'number': 1458,
 'ending': 579,
 'award': 114,
 'match': 1231,
 'quoting': 1700,
 'standard': 1974,
 'app': 72,
 'today voda': 2140,
 'voda number': 2306,
 'number ending': 1460,
 'ending selected': 580,
 'receive award': 1729,
 'match please': 1232,
 'call quoting': 253,
 'quoting claim': 1701,
 'code standard': 363,
 'standard rate': 1975,
 'mu': 1363,
 'buying': 223,
 'wat time': 2353,
 'time finish': 2122,
 'sent': 1857,
 'bother': 192,
 'sending': 1855,
 'del': 492,
 'bak': 130,
 'long time': 1156,
 'give call': 761,
 'dear call': 482,
 'answer': 61,
 'sunshine': 2030,
 'quiz': 1698,
 'top': 2154,
 'sony': 1942,
 'dvd': 557,
 'player': 1589,
 'country': 429,
 'sp': 1953,
 'tyrone': 2209,
 'sunshine quiz': 2031,
 'sony dvd': 1943,
 'player know': 1590,
 'know country': 1041,
 'laid': 1050,
 'dogging': 527,
 'direct': 514,
 'join': 999,
 'largest': 1060,
 'bt': 211,
 'txting': 2203,
 'nt': 1453,
 'ec': 566,
 'want get': 2337,
 'want real': 2342,
 'sent direct': 1858,
 'ur mob': 2253,
 'join uk': 1000,
 'uk largest': 2212,
 'largest dogging': 1061,
 'haf': 842,
 'yijue': 2491,
 'chat': 322,
 'age': 29,
 'yr': 2496,
 'go get': 772,
 'lazy': 1082,
 'type': 2207,
 'lect': 1097,
 'sir': 1902,
 'mail': 1207,
 'sir waiting': 1903,
 'swt': 2046,
 'tired': 2127,
 'little': 1137,
 'lovable': 1169,
 'person': 1558,
 'coz': 433,
 'heart': 867,
 'gud': 831,
 'ni': 1422,
 'gud ni': 834,
 'open': 1503,
 'ya': 2471,
 'yes see': 2487,
 'whats': 2395,
 'taking': 2052,
 'replied': 1749,
 'sexy': 1869,
 'local': 1145,
 'luv': 1197,
 'netcollex': 1405,
 'ltd': 1188,
 'per msg': 1555,
 'reply stop': 1753,
 'stop end': 1995,
 'begin': 149,
 'qatar': 1689,
 'pray': 1649,
 'hard': 860,
 'got job': 806,
 'wine': 2412,
 'thk': 2104,
 'need go': 1401,
 'shirt': 1875,
 'sometimes': 1939,
 'dream': 543,
 'without': 2422,
 'joy': 1006,
 'tv': 2186,
 'become': 144,
 'leaving': 1096,
 'house': 920,
 'interview': 970,
 'boy': 199,
 'missing': 1299,
 'arrange': 86,
 'new year': 1418,
 'receive cash': 1730,
 'cash holiday': 295,
 'keep': 1017,
 'safe': 1799,
 'everyone': 612,
 'miss already': 1294,
 'parent': 1537,
 'hand': 849,
 'new job': 1412,
 'spend': 1963,
 'make happy': 1212,
 'inviting': 975,
 'frnd': 717,
 'inviting friend': 976,
 'friend reply': 713,
 'reply yes': 1754,
 'see www': 1836,
 'www sm': 2460,
 'stop send': 1998,
 'send stop': 1853,
 'stop frnd': 1997,
 'order': 1516,
 'content': 414,
 'goto': 809,
 'internet': 969,
 'menu': 1261,
 'ur mobile': 2254,
 'urgent trying': 2267,
 'wit': 2419,
 'fancy': 634,
 'completely': 394,
 'also': 50,
 'waste': 2350,
 'bank': 133,
 'hmmm': 891,
 'hop': 905,
 'muz': 1377,
 'discus': 519,
 'liao': 1114,
 'coming': 387,
 'time coming': 2121,
 'bloody': 172,
 'hell': 870,
 'cant': 280,
 'believe': 151,
 'mr': 1345,
 'ill': 947,
 'bath': 136,
 'carlos': 288,
 'got money': 807,
 'staying': 1984,
 'til': 2118,
 'smoke': 1924,
 'worth': 2444,
 'doesnt': 525,
 'log': 1147,
 'spoke': 1966,
 'experience': 624,
 'offer': 1469,
 'especially': 599,
 'studying': 2014,
 'gr': 811,
 'trust': 2175,
 'guy': 838,
 'bye': 227,
 'working': 2439,
 'towards': 2161,
 'mummy': 1366,
 'boytoy': 200,
 'awesome': 122,
 'minute': 1286,
 'freephone': 706,
 'xmas': 2466,
 'jus': 1010,
 'bathe': 137,
 'si': 1887,
 'using': 2275,
 'reached home': 1717,
 'unique': 2223,
 'th': 2088,
 'co uk': 360,
 'joined': 1001,
 'touch': 2158,
 'deal': 480,
 'personal': 1561,
 'keep touch': 1021,
 'finally': 660,
 'course': 431,
 'however': 922,
 'stay': 1983,
 'able': 2,
 'every': 608,
 'gr day': 812,
 'mrng': 1346,
 'hav': 862,
 'gud mrng': 833,
 'mrng dear': 1347,
 'nice day': 1424,
 'story': 2006,
 'person story': 1560,
 'dead': 479,
 'tmr': 2130,
 'orchard': 1515,
 'mrt': 1348,
 'kate': 1015,
 'evening': 606,
 'see tomorrow': 1835,
 'found': 691,
 'buck': 215,
 'gt buck': 821,
 'darlin': 463,
 'ive': 986,
 'college': 374,
 'decimal': 487,
 'balance': 131,
 'transaction': 2166,
 'id': 941,
 'lt decimal': 1185,
 'decimal gt': 488,
 'goodmorning': 800,
 'sleeping': 1915,
 'dat': 466,
 'oso': 1523,
 'cannot': 279,
 'oredi': 1519,
 'like dat': 1124,
 'straight': 2009,
 'connection': 406,
 'bill': 159,
 'big': 158,
 'ready': 1721,
 'get ready': 747,
 'break': 203,
 'semester': 1846,
 'hope great': 908,
 'study': 2013,
 'noe': 1433,
 'leh': 1102,
 'sound': 1950,
 'slept': 1916,
 'past': 1546,
 'easy': 561,
 'sen': 1847,
 'exam': 617,
 'march': 1226,
 'atm': 102,
 'ok prob': 1484,
 'called': 261,
 'important': 953,
 'file': 655,
 'system': 2047,
 'shop': 1877,
 'happen': 851,
 'romantic': 1782,
 'nite': 1431,
 'collect': 370,
 'tc': 2059,
 'biz': 166,
 'optout': 1510,
 'gbp': 737,
 'mtmsg': 1361,
 'new mobile': 1414,
 'txt nokia': 2193,
 'appreciate': 75,
 'partner': 1542,
 'career': 287,
 'start': 1977,
 'star': 1976,
 'sign': 1892,
 'company': 391,
 'bcoz': 141,
 'teach': 2062,
 'good morning': 797,
 'walk': 2326,
 'road': 1779,
 'side': 1889,
 'street': 2010,
 'battery': 138,
 'died': 506,
 'flirt': 677,
 'sam': 1806,
 'name age': 1382,
 'bus stop': 220,
 'wil': 2406,
 'reach': 1714,
 'argument': 81,
 'kick': 1028,
 'person dont': 1559,
 'ur friend': 2245,
 'secret': 1830,
 'admirer': 18,
 'reveal': 1766,
 'secret admirer': 1831,
 'admirer looking': 19,
 'looking make': 1163,
 'make contact': 1210,
 'contact find': 409,
 'find reveal': 664,
 'reveal think': 1767,
 'think ur': 2101,
 'ur special': 2258,
 'special call': 1960,
 'laptop': 1058,
 'case': 290,
 'tel': 2067,
 'meant': 1247,
 'told': 2142,
 'face': 629,
 'watch': 2354,
 'fr': 692,
 'thanx': 2093,
 'everything': 613,
 'website': 2368,
 'asked': 96,
 'kallis': 1013,
 'didnt': 503,
 'goodnight': 802,
 'fix': 672,
 'wake': 2324,
 'sleep': 1913,
 'oh ok': 1477,
 'good night': 798,
 'congratulation': 404,
 'cd': 303,
 'voucher': 2311,
 'gift': 755,
 'music': 1373,
 'tncs': 2131,
 'ldew': 1083,
 'ppmx': 1645,
 'congratulation ur': 405,
 'voucher gift': 2314,
 'gift guaranteed': 756,
 'draw txt': 542,
 'txt music': 2192,
 'music tncs': 1375,
 'tncs www': 2132,
 'www ldew': 2459,
 'ldew com': 1084,
 'com win': 380,
 'win ppmx': 2411,
 ...}

In [44]:
#output features
y=pd.get_dummies(messages['label'], dtype=int)

In [45]:
y.head()

   ham  spam
0    1     0
1    1     0
2    0     1
3    1     0
4    1     0

In [46]:
y=y.iloc[:,0].values

In [47]:
#traintestsplit
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [48]:
from sklearn.naive_bayes import MultinomialNB

In [49]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [50]:
y_pred=spam_detect_model.predict(X_test)

In [51]:
from sklearn.metrics import accuracy_score,classification_report

In [52]:
y.shape

(5572,)

In [53]:
accuracy_score(y_test,y_pred)

0.9838565022421525

In [54]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.94      0.94       160
           1       0.99      0.99      0.99       955

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115

Using tfidf model for spam classification

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X1=tfidf.fit_transform(corpus).toarray()

In [56]:
#traintestsplit
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.20)

In [57]:
spam_detect_model1=MultinomialNB().fit(X_train,y_train)
y_pred1=spam_detect_model1.predict(X_test)

In [58]:
accuracy_score(y_test,y_pred1)

0.9775784753363229

In [59]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.12      0.12      0.12       158
           1       0.85      0.85      0.85       957

    accuracy                           0.75      1115
   macro avg       0.49      0.49      0.49      1115
weighted avg       0.75      0.75      0.75      1115