In [31]:
import pandas as pd
data = pd.read_csv("kindle_reviews.csv",nrows=12000)

In [32]:
data.head()

,Unnamed: 0,asin,helpful,overall,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,B000F83SZQ,"[0, 0]",5,I enjoy vintage books and movies so I enjoyed ...,"05 5, 2014",A1F6404F1VG29J,Avidreader,Nice vintage story,1399248000
1,1,B000F83SZQ,"[2, 2]",4,This book is a reissue of an old one; the auth...,"01 6, 2014",AN0N05A9LIJEQ,critters,Different...,1388966400
2,2,B000F83SZQ,"[2, 2]",4,This was a fairly interesting read. It had ol...,"04 4, 2014",A795DMNCJILA6,dot,Oldie,1396569600
3,3,B000F83SZQ,"[1, 1]",5,I'd never read any of the Amy Brewster mysteri...,"02 19, 2014",A1FV0SX13TWVXQ,"Elaine H. Turley ""Montana Songbird""",I really liked it.,1392768000
4,4,B000F83SZQ,"[0, 1]",4,"If you like period pieces - clothing, lingo, y...","03 19, 2014",A3SPTOKDG7WBLN,Father Dowling Fan,Period Mystery,1395187200

In [33]:
data=data[['reviewText','overall']]
data.head()

                                          reviewText  overall
0  I enjoy vintage books and movies so I enjoyed ...        5
1  This book is a reissue of an old one; the auth...        4
2  This was a fairly interesting read.  It had ol...        4
3  I'd never read any of the Amy Brewster mysteri...        5
4  If you like period pieces - clothing, lingo, y...        4

In [34]:
data['overall'].unique()

array([5, 4, 3, 2, 1], dtype=int64)

In [35]:
data.shape

(12000, 2)

In [36]:
!pip install ydata-profiling
from ydata_profiling import ProfileReport

Requirement already satisfied: ydata-profiling in c:\users\hp\anaconda3\lib\site-packages (4.18.1)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (1.13.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (3.9.2)
Requirement already satisfied: pydantic<3,>=2 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (2.8.2)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\hp\anaconda3\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (1.26.4)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (4.66.5)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (0.14.2)
Requirement already satisfied: typeguard<5,>=4 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\hp\anaconda3\lib\site-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in c:\users\hp\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.7.0)
Requirement already satisfied: pillow in c:\users\hp\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\users\hp\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2023.3)
Requirement already satisfied: joblib>=0.14.1 in c:\users\hp\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\hp\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\hp\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\hp\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2024.12.14)
Requirement already satisfied: patsy>=0.5.6 in c:\users\hp\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (0.5.6)
Requirement already satisfied: colorama in c:\users\hp\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\hp\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in c:\users\hp\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.3)
Requirement already satisfied: puremagic in c:\users\hp\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.1.0)
Requirement already satisfied: six in c:\users\hp\anaconda3\lib\site-packages (from patsy>=0.5.6->statsmodels<1,>=0.13.2->ydata-profiling) (1.16.0)

In [37]:
profile=ProfileReport(data,title="review analysis report",explorative=True)

In [38]:
profile.to_file("analysis_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 2/2 [00:01<00:00,  1.42it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

check null values as dataset is large so we remove null value when only few na values is there

In [39]:
data.isnull().sum()

reviewText    0
overall       0
dtype: int64

In [40]:
data['overall'].value_counts()

overall
5    5508
4    3591
3    1682
2     706
1     513
Name: count, dtype: int64

In [41]:
data['overall']=data['overall'].apply(lambda x:0 if x<4 else 1)

In [42]:
data.head()

                                          reviewText  overall
0  I enjoy vintage books and movies so I enjoyed ...        1
1  This book is a reissue of an old one; the auth...        1
2  This was a fairly interesting read.  It had ol...        1
3  I'd never read any of the Amy Brewster mysteri...        1
4  If you like period pieces - clothing, lingo, y...        1

In [43]:
data['reviewText']=data.reviewText.str.lower()

In [44]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [45]:
from bs4 import BeautifulSoup

In [46]:

stop_words = set(stopwords.words("english"))

def clean_text(x):
    x = re.sub(r'http\S+|www\S+', '', x)          #remove url
    x = BeautifulSoup(x,'lxml').get_text()       #remove html
    x = re.sub(r'[^a-zA-Z0-9 ]+', '', x)         #special chars
    x = " ".join([w for w in x.split() if w not in stop_words]) #stopwords
    x = " ".join(x.split())                      #extra spaces
    return x

data['reviewText'] = data['reviewText'].apply(clean_text)

C:\Users\hp\AppData\Local\Temp\ipykernel_19556\2728290414.py:5: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  x = BeautifulSoup(x,'lxml').get_text()       #remove html

In [47]:
data.head()

                                          reviewText  overall
0  enjoy vintage books movies enjoyed reading boo...        1
1  book reissue old one author born 1910 era say ...        1
2  fairly interesting read old style terminologyi...        1
3  id never read amy brewster mysteries one reall...        1
4  like period pieces clothing lingo enjoy myster...        1

In [48]:
#lemmatizer
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [49]:
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [50]:
from nltk import pos_tag

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [51]:
def lemmatizeword(text):
    return " ".join([lemmatizer.lemmatize(word,'v') for word in text.split()])

In [52]:
data['reviewText']=data['reviewText'].apply(lambda x: lemmatizeword(x))

In [53]:
data.head()

                                          reviewText  overall
0  enjoy vintage book movies enjoy read book plot...        1
1  book reissue old one author bear 1910 era say ...        1
2  fairly interest read old style terminologyi gl...        1
3  id never read amy brewster mysteries one reall...        1
4  like period piece clothe lingo enjoy mystery a...        1